version: '3.7'

services:
  invoiceninja-tailscale:
    image: tailscale/tailscale:latest
    container_name: invoiceninja-tailscale
    hostname: invoiceninja
    environment:
      - TS_AUTHKEY=tskey-auth-k8JyaeqfWT11CNTRL-zfqYRAHScWiPyhbsEGrzciTDatajqn62?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/invoiceninja.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/invoiceninja-tailscale/state:/var/lib/tailscale
      - ${PWD}/invoiceninja-tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  
  invoiceninja-server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja-app
      - invoiceninja-tailscale
    network_mode: service:invoiceninja-tailscale
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    #ports:
     # - "8034:80"
      #- "443:443"
    #networks:
     # - invoiceninja
    extra_hosts:
      - "in5.test:192.168.1.11 " #host and ip

  invoiceninja-app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini

    depends_on:
      - invoiceninja-db
      - invoiceninja-tailscale
    network_mode: service:invoiceninja-tailscale
    #networks:
    #  - invoiceninja
    #extra_hosts:
    #  - "in5.test:192.168.1.11 " #host and ip

  invoiceninja-db:
    image: mysql:8
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    depends_on:
      - invoiceninja-tailscale
    network_mode: service:invoiceninja-tailscale
    #networks:
    #  - invoiceninja
    #extra_hosts:
    #  - "in5.test:192.168.1.11 " #host and ip

#networks:
#  invoiceninja:

volumes:
  invoiceninja-tailscale:
    driver: local
