version: '3.7'

services:

  invoiceninja-server-ts:
    image: tailscale/tailscale:latest
    container_name: invoiceninja-server-ts
    hostname: invoiceninja-server
    environment:
      - TS_AUTHKEY=tskey-auth-kySCaTdmXv11CNTRL-Lahskomf8ffBXP8CQcNmnfV2ntz8Ubtk7
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale/server.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  
  invoiceninja-server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja-app
      - invoiceninja-server-ts
    network_mode: service:invoiceninja-server-ts

  invoiceninja-app-ts:
    image: tailscale/tailscale:latest
    container_name: invoiceninja-app-ts
    hostname: invoiceninja-app
    environment:
      - TS_AUTHKEY=tskey-auth-kySCaTdmXv11CNTRL-Lahskomf8ffBXP8CQcNmnfV2ntz8Ubtk7
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  invoiceninja-app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini

    depends_on:
      - invoiceninja-db
      - invoiceninja-app-ts
    network_mode: service:invoiceninja-app-ts

  invoiceninja-db-ts:
    image: tailscale/tailscale:latest
    container_name: invoiceninja-db-ts
    hostname: invoiceninja-db
    environment:
      - TS_AUTHKEY=tskey-auth-kySCaTdmXv11CNTRL-Lahskomf8ffBXP8CQcNmnfV2ntz8Ubtk7
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale/db.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  invoiceninja-db:
    image: mysql:8
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    depends_on:
      - invoiceninja-db-ts
    network_mode: service:invoiceninja-db-ts

volumes:
  invoiceninja-app-ts:
    driver: local
  invoiceninja-server-ts:
    driver: local
  invoiceninja-db-ts:
    driver: local
